---
- name: Download
  ansible.builtin.get_url:
    url: "{{ file_url }}"
    dest: "{{ install_path }}"
    # checksum: "md5:{{ file_url }}.md5"

- name: Ensure target folder exists
    file:
      dest: "{{ install_path }}"
      state: directory
      mode: '775'
      owner: vagrant
      group: vagrant

- name: Unpack
  ansible.builtin.unarchive:
    src: "{{ install_path }}/{{ file_url | basename }}/"
    dest: "{{ install_path }}"
