---
- name: Download
  ansible.builtin.get_url:
    url: "{{ file_url }}"
    dest: "{{ target_folder }}"
    # checksum: "md5:{{ file_url }}.md5"

- name: Unpack
  ansible.builtin.unarchive:
    src: "{{ target_folder }}/{{ file_url | basename }}"
    dest: "{{ target_folder }}"
