---
- name: Download
  ansible.builtin.get_url:
    url: "{{ file_url }}"
    dest: "{{ install_path }}"
    # checksum: "md5:{{ file_url }}.md5"

- name: Unpack
  ansible.builtin.unarchive:
    src: "{{ install_path }}/{{ file_url | basename }}/"
    dest: "{{ install_path }}"
